# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 05:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_remove_bookinstance_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinstance",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Fishcakes instance+",
                to="catalog.Book",
            ),
        ),
    ]
