name: Python / Django

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [fmt, lint, mypy]
    env:
      TOXENV: ${{ matrix.toxenv }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python (3.11)
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install and run tox
        run: |
          pip install tox
          tox

  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12]
        django: ["32", "40", "41", "42", "50", "main"]
        exclude:
          - python: "3.8"
            django: "50"
          - python: "3.8"
            django: "main"
          - python: "3.9"
            django: "50"
          - python: "3.9"
            django: "main"
          - python: "3.10"
            django: "main"
          - python: "3.11"
            django: "32"
          - python: "3.11"
            django: "40"
          - python: "3.12"
            django: "32"
          - python: "3.12"
            django: "40"

    env:
      TOXENV: django${{ matrix.django }}-py${{ matrix.python }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install and run tox
        run: |
          pip install tox
          tox
